<?php

namespace AppBundle\Repository;

/**
 * PhoneBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneBookRepository extends \Doctrine\ORM\EntityRepository
{
}
