<?php

namespace AppBundle\Repository;

/**
 * Session_msgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Session_msgRepository extends \Doctrine\ORM\EntityRepository
{
}
