<?php

namespace AppBundle\Repository;

/**
 * Traking_msgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Traking_msgRepository extends \Doctrine\ORM\EntityRepository
{
}
