<?php

namespace AppBundle\Repository;

/**
 * UTM_paramsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UTM_paramsRepository extends \Doctrine\ORM\EntityRepository
{
}
