getAll:
    path:     /users
    defaults: { _controller: AppBundle:PhoneBook:getAll }
    methods:    [GET]

get:
    path:     /users/search/{name}
    defaults: { _controller: AppBundle:PhoneBook:get }
    methods:    [GET]

post:
    path:     /users
    defaults: { _controller: AppBundle:PhoneBook:post }
    methods:    [POST]

put:
    path:     /users/{id}
    defaults: { _controller: AppBundle:PhoneBook:put }
    methods:    [PUT]

delete:
    path:     users/delete/{id}
    defaults: { _controller: AppBundle:PhoneBook:delete }
    methods:    [DELETE]
