get:
    path:     /get
    defaults: { _controller: AppBundle:PhoneBook:get }
    methods:    [GET]

post:
    path:     /post
    defaults: { _controller: AppBundle:PhoneBook:post }
    methods:    [POST]

put:
    path:     /put
    defaults: { _controller: AppBundle:PhoneBook:put }
    methods:    [PUT]

delete:
    path:     /delete
    defaults: { _controller: AppBundle:PhoneBook:delete }
    methods:    [DELETE]
