AppBundle\Entity\SessionMsg:
    type: entity
    table: session_msg
    uniqueConstraints:
        sesson_msg_id_key:
            columns:
                - id
    id:
        sessId:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            id: true
            column: sess_id
            generator:
                strategy: SEQUENCE
    fields:
        sessData:
            type: blob
            nullable: false
            length: null
            options:
                fixed: false
            column: sess_data
        sessTime:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: sess_time
        sessLifetime:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: sess_lifetime
        id:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
