AppBundle\Entity\Session_msg:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Session_msgRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cid:
            type: string
            length: 255
        sid:
            type: string
            length: 255
            nullable: true
        uid:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
