AppBundle\Entity\UTM_params:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UTM_paramsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        source:
            type: string
            length: 255
            nullable: true
        content:
            type: string
            length: 255
            nullable: true
        campaign:
            type: string
            length: 255
            nullable: true
        medium:
            type: string
            length: 255
            nullable: true
        term:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        utm_params:
            targetEntity: Traking_msg
            mappedBy: UTM_params
            onDelete: CASCADE
