AppBundle\Entity\Visitors:
    type: entity
    table: visitors
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        ip:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lg:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        rf:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        ua:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
